
[functions.crear-preferencia-mp]
enabled = true
verify_jwt = true
import_map = "./functions/crear-preferencia-mp/deno.json"
entrypoint = "./functions/crear-preferencia-mp/index.ts"

[functions.mp-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/mp-webhook/index.ts"
